---
title: "Introduction and Workflow"
output: html_document
date: "2025-11-15"
bibliography: "C:/Users/Owner/Documents/UO Master's/Classes/Data Science Eco Conserv/Bumble bee Network.bib"
---
### *Introduction*
  Bumble bees are important pollinators in montane ecosystems, pollinating a wide variety of flower species in high elevation meadows [@devoto_ecological_2014]. These services that they provide are vital for the maintenance of the health of this ecosystem. Bumble bees display central place foraging; workers gather resources on foraging bouts and bring pollen and nectar back to the colony after every foraging cycle, supporting colony health throughout the season [@kembro_bumblebees_2019]. Bumble bees therefore are limited in their dispersal capacity as individuals are expected to return to their nests after each foraging bout; resources are not gathered for the individual but for the colony [@kembro_bumblebees_2019]. Bumble bees historically begin foraging during peak floral abundance, and senesce when flowers begin senescing as well. The life cycle of annual flowers and bumble bees are therefore highly linked. 

In high elevation ecosystems various climatic conditions act as drivers for flower and bumble bee phenology[@ogilvie_interannual_2017]. Past research has shown that the strongest drivers are precipitation, seasonal snow melt timing, and temperature [@ogilvie_interannual_2017][@millerstruttmann_climate_2022], with various positive and negative effects. For example, while precipitation may lead to sooner bloom periods, too much precipitation might negatively effect bumble bees by damaging nests[@millerstruttmann_climate_2022]. In years past, timing to first flower bloom and queen emergence have been synchronized in ways such that bumble bee colony abundance corresponds to peak floral resource availability; however, climate change is a suspected driver of current observed phenological mismatch between bumble bees and flowers, which may have the power to reshape plant-pollinator networks [@millerstruttmann_climate_2022]. Climate change is a suspected driver of phenological mismatch because variation in climate conditions heavily impacts various attributes of flower species, which can have downstream effects on pollinators. While average temperatures in May in high elevation environments act a cue for both flower blooms and bee emergence and foraging initiation, when May temperatures are warmer, flowers begin blooming earlier [@millerstruttmann_climate_2022]. Greater summer precipitation and later snowmelt days lengthen floral days, which increases bumble bee abundance, and summer precipitation advances worker emergence [@ogilvie_interannual_2017][@millerstruttmann_climate_2022].  However, though floral season has lengthened, it has also been observed that floral days decrease, negatively impacting bumble bee abundance, suggesting that while lengthened floral periods may increase bee abundance, reduced  floral abundance has negative impacts on bumble bee health [@ogilvie_interannual_2017]. Overall, it has been observed that warmer May temperatures lead to greater phenological mismatch between flowers and pollinators, which has potential negative effects on bumble bee health as resources depleted earlier in the season reduce the length of the foraging period for bumble bees[@millerstruttmann_climate_2022]. It is therefore important to investigate diet breadth plasticity throughout time in bumble bee species. 
Bumble bee foraging may be limited by physiological constraints, potentially influencing the ability of bumble bees to forage on particular flower species[@martin_diversified_2025]. Specifically, length of bumble bee tongues have been a suspected driver of niche partitioning, as longer tongued bees can forage better from flowers with deeper corolla lengths, leading to potential foraging specialization (reviewed by [@martin_diversified_2025]. However, recent studies have suggested that variation in tongue length in alpine bumble bees is becoming homogenized because of climate change acting as a selective pressure (reviewed by [@martin_diversified_2025]), and yet tongue homogenization is not a predicted driver of niche partitioning as variation in tongue length does not predict modules in plant-pollinator networks in alpine bumble bees [@martin_diversified_2025]. Therefore, we expect other drivers, such as other behavioral traits, to influence foraging of bumble bees under the pressure of climate change [@martin_diversified_2025]. Bumble bees are highly adaptive foragers that shift between habitual and stochastic foraging trends, allowing them to both exploit resources and explore for novel resource acquisition [@kembro_bumblebees_2019]. In environments that are experiencing phenological mismatch, this ability to switch resources might allow for individual persistence in changing conditions [@ponisio2017opportunistic]. 
	
	Previous work by [@ponisio2017opportunistic], has investigated opportunistic attachment processes in plant-pollinator networks [@ponisio2017opportunistic]. Opportunistic attachment suggest that generalist species, when context changes and different resources are available, switch opportunistically to foraging on different resources rather than sticking to one or a set of predictable and consistent resources [@ponisio2017opportunistic]. Compared to preferential attachment, in a network experiencing opportunistic attachment, it is predicted that network nestedness does not generate through time as individuals are changing their resource usage creating novel interactions, which has been investigated through species turn over [@ponisio2017opportunistic]. In this system, change points- which are changes in modules in a network, including both formation of modules and dissolving of modules- can act as an indicator of opportunistic attachment. [@ponisio2017opportunistic]. In this study, data was collected over a period of 8 years along hedgerows in Central CA; plant-pollinator networks were constructed from bee samples as well as syrphids [@ponisio2017opportunistic]. This study differs from my focus as I will only be focusing on bumble bee species, investigating opportunistic attachment in bumble bees across a period of data collected from 2011 to 2024. To test for opportunistic attachment, Ponisio et al., investigated significant reorganizations in network assembly, variability in network position for each species, as well as turnover throughout time for these species investigated [@ponisio2017opportunistic]. Considering the data I will be using is similar to the data the Ponisio et al., collected and analyzed, my work will be highly inspired by this study. 

	To calculate change point analysis I can use the methodology suggested in [@ponisio2017opportunistic]. However, a limitation pointed out in this study is that there has been no standardizations for change point analyses up to the time in which the paper was written, and that change point detection methods are only able to be used with binary data. The paper [@ponisio2017opportunistic] lists a step by step methodology on how to use various programs to calculate change points, as well as providing a link to the study’s repository; for now, I will keep this as an idea for analyzing data and communicate with Lauren about this in my next one-on-one for further suggestions/updates. 

	Following the framework of [@ponisio2017opportunistic], I will:

-	Calculate species persistence:
Proportion of surveys in which a plant or pollinator is observed across the years of the data set- higher proporitions suggest greater persistence in the network

-	Degree: 
Allows us to estimate plant-pollinator interactions that were not collected from insufficient sampling

-	Closeness centrality:
By calculating the path network lengths of one species to another species, the importance of that species can be determined. I can compare centrality mean lengths of species to other species to determine their closeness, and as has been done in Ponisio et al., determine if the variability in closeness is related to calculated persistence and degree. 

-	The paper investigated species turnover throughout time by calculating turnover at sites throughout the years [@ponisio2017opportunistic]. In this investigation, they calculated the dissimilarity between plants and pollinators and the plant and pollinator interactions, incorporating in abundances for both plants and pollinators, as it is expected for dissimilarity measures to be higher when there are less abundant species as we would expect less interactions between these species. Using the methodology proposed by [@ponisio2017opportunistic], I can calculate turnover throughout time through using these dissimilarity measures, which can be calculated using a dissimilarity estimator. This will allow me to detect changes in plant pollinator usages throughout each year instead of just looking at changes throughout just the singular year, allowing me to make predictions about changes in networks over time. 

-	I will also calculate the following metrics: connectance, nestedness, change in plant-pollinator richness, and modularity. Using these metrics, I can investigate network dynamics to inform me about network processes. 

Investigating these dynamics in bumble bees is relevant because flowers may senesce before the end of the foraging season in bumble bees because of climate conditions, which may limit resource availability for bumble bees and have downstream effects on bumble bee colony health. This may force bumble bees to switch to different resources to forage from, and we’d expect to see this as a seasonal shift if bumble bees are able to switch the resources that they use. I am interested in this as it shows adaptation to changes in local conditions and may be a driver of species persistence in changing climate conditions. For species that are more specialized than generalized foragers, investigating diet breadth in bumble bees will inform us about foraging behaviors in bumble bees. 

### *Hypotheses/Questions:*

Questions:

What are the overall foraging trends that can be observed in bumble bee networks across the 2011-2024 data set at HJ Andrews, as analyzed through network construction?

Do bumble bees shift foraging to novel resources throughout the season as other resources deplete, or do bumble bees display preferential foraging for a selection of floral resources?

Do we observe foraging plasticity throughout the years in bumble bees, as shown by novel interactions in plant-pollinator networks? 

Do bumble bees display opportunistic or preferential attachment processes when foraging? 

Hypothesis: Among bumble bee populations collected at HJ Andrews Experimental Forest, through analysing networks in bumble bee populations, these networks will display opportunistic foraging attachment strategies with an increased shift towards displaying this foraging strategy throughout the years from 2011 to 2024, with 2024 populations displaying the highest degree of an opportunistic attachment process. It is predicted that there will be lower degrees of nestedness detected and higher degrees of novel bumble bee plant interactions.

Alternative hypothesis: Bumble bee populations will not display shifts in foraging strategies throughout the year, and bumble bee networks will show bumble bee foraging processes to be preferentially attached. There will be no change in bumble bee plant interactions and nestedness throughout the years. 

Dataset Identification: 

 The data that will be used are data collected for the LTER pollinator data from HJ Andrews Experimental Forest Cascades Meadow data. Path: "C:/Users/Owner/University of Oregon Dropbox/Megan Fenner/cascades-meadows/dataPrep/1_specimenPrep.R"

The data were collected using standardized sampling protocol at three meadow complexes. Plants were identified, counted, and bloom status as well as the number of blooms recorded. Pollinators were sampled at each complex. These pollinators were identified. Within this data set, date of collection, collector, sample round, site, meadow complex, pollinator ID, plant ID, plant count for each plot, bloom status for each plant for each sample round at each plot in each meadow complex, and number of flowers were collected. The data also includes functions that are used to calculate various network metrics; these metric calculations are also included int eh data set, but the overall network includes every pollinator sampled, not just bumble bees, as is my focus. 

### *Workflow Proposal*

The HJA dataframe “spec.net” include an extensive amount of columns, including but not limited to sampler, sample date, meadow complex, meadow plot, various weather data, and data for the pathogen experiment. Therefore, there will need to be some massive data cleaning such that isolate only the columns that I am interested in. Luckily for me, the raw data have been processed and joined to create the “spec.net” dataframe, which I will be working out of. Specifically, these columns that I am interested in are:
Year, Site, Sample Round, Date, Genus, GenusSpecies, PlantGenus or PlantGenusSpecies, and Complex- site might suffice and therefore complex might not be needed.  

Of the HJA Genus, I will filter out data to the genus Bombus, compiling only data for the bumble bee species. In theory, this will generate a new data frame that includes every individual bumble bee that has been caught throughout the years. Hopefully, this will clean up the data frame by excluding all the data associated with the other species that were caught. 

The vegetation data do not need to be filtered out any more than cleaning up the dataframe to only include the PlantGenus or PlantGenusSpecies data. Because the data set includes the plants that pollinators interacted with, we do not need to further filter out plant data to only include the plants that have associations with pollinators, as there is a data set which includes more plant specific data called “veg.blooming”. However, we will have to make sure that when filtering out data for only the genus Bombus, we also make sure that the vegetation data get carried over as well; as would be predicted by using these functions. 

I will then use the function “makeNets” which is a function created and available in the repository for the cascades meadows. I will have to make sure that I include the updated dataframe that only includes bumble bees, as outlined in the steps above.

There is a potential that modifications to the plant data frames trickle into the networks that are further built. Extracting data from the “spec” dataframe, visitor plant abundance for the focal plant species (line 697), and average network metrics from the blooming period of each spp. (line 715)- which includes mean closeness, mean betweenness, mean rare degree, mean degree, and mean d are calculated and stored-, have been calculated using the full data set spec. We will be modifying a dataset that includes these values as well; considering that our network will be constructed using both plant and pollinator data, we will have to reconstruct this code as well to include the data for only bumble bees. 
On line 830, it outlines how to calculate vegetation abundance, vegetation richness, and vegetation diversity out of the veg data (as these data include number of blooms, which the spec data do not include). This can be helpful just to get base level statistics, and should be outlined in the workflow.

To analyze the data at an even smaller time scale, we can look at the metrics for a network in the created “makeNets” function on line 13 in the folder “prepNets.R” by choosing the “net.type” in the function to be “YearSR”, which stands for “year and sampling round”. Therefore, it creates a network by year and sampling round instead of just “Year” which you can achieve by simply inputting “Year” into the “net.type”. 

### *References*
Ogilvie, J. E., Griffin, S. R., Gezon, Z. J., Inouye, B. D., Underwood, N., Inouye, D. W., & Irwin, R. E. (2017). Interannual bumble bee abundance is driven by indirect climate effects on floral resource phenology. Ecology letters, 20(12), 1507-1515.

Miller‐Struttmann, N., Miller, Z., & Galen, C. (2022). Climate driven disruption of transitional alpine bumble bee communities. Global Change Biology, 28(21), 6165-6179.

Martin, V., Galen, C., & Miller-Struttmann, N. E. (2025). Diversified but not redundant: upslope migrating bumble bees restructure pollination services to alpine plants. Oikos, e11443.

Kembro, J. M., Lihoreau, M., Garriga, J., Raposo, E. P., & Bartumeus, F. (2019). Bumblebees learn foraging routes through exploitation–exploration cycles. Journal of the Royal Society Interface, 16(156), 20190103.

Ponisio, L. C., Gaiarsa, M. P., & Kremen, C. (2017). Opportunistic attachment assembles plant–pollinator networks. Ecology Letters, 20(10), 1261-1272.


